Repository typed-ember/glint, pull requests merged in 2021-03, with the labels that each got.

#79 Show using `glint` to replace `tsc --noEmit`
  README.md
Labels: documentation

#80 Fix `each` not working with a `readonly` array
  packages/template/-private/keywords/each.d.ts
  packages/template/__tests__/keywords/each.test.ts
Labels: bug

#78 Adding server debugging support in launch.json and extension.ts, added sourceMap to tsconfig
  .gitignore
  .vscode/launch.json
  packages/vscode/src/extension.ts
  tsconfig.compileroptions.json
Labels: internal

#97 build before launch in Debug Extension
  .vscode/launch.json
Labels: internal

#95 Performance improvements
  packages/core/src/common/transform-manager.ts
  packages/core/src/language-server/index.ts
  packages/transform/src/index.ts
Labels: enhancement

#109 Type primary elements properly for built-in components
  packages/environment-ember-loose/-private/intrinsics/component.d.ts
  packages/environment-ember-loose/-private/intrinsics/input.d.ts
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/-private/intrinsics/textarea.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/input.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/textarea.test.ts
  packages/template/-private/integration.d.ts
Labels: bug

#113 `LinkTo`: support `@models` and fix required args
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
Labels: bug

#112 Support inverse for {{#each-in}} - Fixes #108
  packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/each-in.test.ts
Labels: bug

#115 Support SafeString - Fixes #93
  packages/template/-private/dsl/invoke.d.ts
  packages/template/__tests__/custom-invokable.test.ts
Labels: bug

#117 Fix Ember Modifier class
  packages/environment-ember-loose/ember-modifier/index.ts
Labels: bug

#114 Support SVGElements - Fixes #99
  packages/template/-private/dsl/types.d.ts
  packages/template/__tests__/attributes.test.ts
Labels: bug

#111 Introduce `ComponentLike` and associated types
  README.md
  packages/environment-ember-loose/-private/index.ts
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
  packages/environment-ember-loose/package.json
Labels: enhancement

#119 Bugfix batch for `environment-ember-loose`
  packages/environment-ember-loose/-private/dsl/globals.d.ts
  packages/environment-ember-loose/-private/intrinsics/each.d.ts
  packages/environment-ember-loose/-private/intrinsics/get.d.ts
  packages/environment-ember-loose/__tests__/helper.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/get.test.ts
  packages/environment-ember-loose/ember-component/helper.ts
Labels: bug
