Repository typed-ember/glint, pull requests merged in 2021-04, with the labels that each got.

#125 Allow {{each}} to handle null and undefined
  packages/environment-ember-loose/-private/intrinsics/each.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
Labels: bug

#131 Don't crash for operations on an unaffiliated template
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/__tests__/language-server/definitions.test.ts
  packages/core/__tests__/language-server/hover.test.ts
  packages/core/__tests__/language-server/references.test.ts
  packages/core/__tests__/language-server/rename.test.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/util/index.ts
Labels: bug

#132 Allow emitting `Element` values
  packages/template/-private/dsl/invoke.d.ts
  packages/template/__tests__/custom-invokable.test.ts
  packages/template/__tests__/invoke-emit.test.ts
Labels: bug

#139 Allow null values for Textarea
  packages/environment-ember-loose/-private/intrinsics/textarea.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/textarea.test.ts
Labels: bug

#140 Don't print declaration diagnostics when we aren't emitting declarations
  packages/core/src/cli/perform-check.ts
Labels: bug

#141 Allow invoking nullable component values
  packages/template/-private/dsl/resolve.d.ts
  packages/template/__tests__/emit-component.test.ts
  test-packages/ts-ember-app/app/components/foo.hbs
  test-packages/ts-ember-app/app/components/wrapper-component.ts
Labels: bug

#144 Ensure the invocation-context 𝛄 doesn't trigger an unused symbol warning
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/template-to-typescript.ts
Labels: bug

#149 Ensure type narrowing propagates downward
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/__tests__/language-server/hover.test.ts
  packages/environment-ember-loose/__tests__/component.test.ts
  packages/environment-ember-loose/__tests__/helper.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/action.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/each-in.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/fn.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/input.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/textarea.test.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/environment-glimmerx/__tests__/helper.test.ts
  packages/template/-private/dsl/emit.d.ts
  packages/template/__tests__/attributes.test.ts
  packages/template/__tests__/custom-invokable.test.ts
  packages/template/__tests__/emit-component.test.ts
  packages/template/__tests__/keywords/component.test.ts
  packages/template/__tests__/keywords/each.test.ts
  packages/template/__tests__/keywords/let.test.ts
  packages/template/__tests__/keywords/with.test.ts
  packages/template/__tests__/resolution.test.ts
  packages/transform/__tests__/debug.test.ts
  packages/transform/__tests__/offset-mapping.test.ts
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/template-to-typescript.ts
Labels: bug

#150 Ensure we reexport static members from upstream classes
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/__tests__/component.test.ts
  packages/environment-ember-loose/__tests__/helper.test.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
Labels: bug

#151 Allow 'on' modifier with SVGElement
  packages/environment-ember-loose/-private/intrinsics/on.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/on.test.ts
Labels: bug

#154 Introduce `PositionalArgs` for component signatures
  README.md
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/__tests__/component-like.test.ts
  packages/environment-ember-loose/__tests__/ember-component.test.ts
  packages/environment-ember-loose/__tests__/glimmer-component.test.ts
  packages/environment-ember-loose/ember-component/index.ts
Labels: enhancement

#155 Remove `Record`-based constraints on signature members
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/__tests__/helper.test.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-glimmerx/component/index.ts
  packages/template/__tests__/resolution.test.ts
  packages/template/__tests__/test-component.ts
Labels: bug

#157 Support ComputedProperty in get helper
  packages/environment-ember-loose/-private/intrinsics/get.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/get.test.ts
Labels: enhancement

#156 Don't block Windows on Linux in CI
  .github/workflows/ci.yml
Labels: internal

#162 Add tests for `in-element`
  packages/template/__tests__/keywords/in-element.test.ts
Labels: internal

#163 Don't prevent subclassing of components with companion templates
  packages/transform/__tests__/rewrite.test.ts
  packages/transform/src/inlining/companion-file.ts
  test-packages/ts-ember-app/app/components/test-cases/subclassing/child.hbs
  test-packages/ts-ember-app/app/components/test-cases/subclassing/child.ts
  test-packages/ts-ember-app/app/components/test-cases/subclassing/parent.hbs
  test-packages/ts-ember-app/app/components/test-cases/subclassing/parent.ts
Labels: bug

#165 Don't crash when requesting diagnostics on an excluded template.
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/language-server/glint-language-server.ts
Labels: bug

#166 Introduce `@glint-ignore` and `@glint-expect-error` directives
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/cli/watch.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/cli/diagnostics.ts
  packages/core/src/cli/perform-check.ts
  packages/core/src/cli/perform-watch.ts
  packages/core/src/common/transform-manager.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/transform/__tests__/debug.test.ts
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/index.ts
  packages/transform/src/inlining/companion-file.ts
  packages/transform/src/inlining/index.ts
  packages/transform/src/inlining/tagged-strings.ts
  packages/transform/src/map-template-contents.ts
  packages/transform/src/template-to-typescript.ts
  packages/transform/src/transformed-module.ts
  test-packages/ts-ember-app/app/components/bar/index.hbs
  test-packages/ts-ember-app/app/components/foo.hbs
  test-packages/ts-ember-app/app/pods/components/baz/template.hbs
  test-packages/ts-ember-app/package.json
  test-packages/ts-ember-app/tests/integration/components/foo-test.ts
  yarn.lock
Labels: enhancement

#171 Allow LinkTo current-when to be boolean
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
Labels: bug

#172 Capture given signatures so TS can infer them from the concrete type
  packages/environment-ember-loose/__tests__/ember-component.test.ts
  packages/environment-ember-loose/__tests__/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/helper.test.ts
  packages/environment-ember-loose/__tests__/modifier.test.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/environment-glimmerx/component/index.ts
Labels: enhancement

#174 Support named args with `{{link-to}}`
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
Labels: bug

#173 Ensure `{{each}}` yields `any` given `any` or a non-iterable value
  packages/environment-ember-loose/-private/intrinsics/each.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
Labels: bug

#176 The `{{component}}` helper silently accepts nullable values
  packages/environment-ember-loose/-private/intrinsics/component.d.ts
  packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
Labels: bug

#175 Prefer `else` over `inverse`
  README.md
  packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
  packages/environment-ember-loose/-private/intrinsics/each.d.ts
  packages/environment-ember-loose/__tests__/component-like.test.ts
  packages/environment-ember-loose/__tests__/ember-component.test.ts
  packages/environment-ember-loose/__tests__/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/each-in.test.ts
  packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/template/-private/keywords/each.d.ts
  packages/template/-private/keywords/with.d.ts
  packages/template/__tests__/custom-invokable.test.ts
  packages/template/__tests__/keywords/with.test.ts
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/template-to-typescript.ts
Labels: breaking

#177 Skip `actions/cache` for Windows CI
  .github/workflows/ci.yml
Labels: internal

#180 Link to `glint-template-types` repo in the README
  README.md
Labels: documentation

#179 Avoid cascading errors on invalid component invocations
  packages/template/-private/dsl/emit.d.ts
  packages/template/-private/integration.d.ts
  packages/template/__tests__/emit-component.test.ts
Labels: bug
