Repository typed-ember/glint, pull requests merged in 2022-12, with the labels that each got.

#487 Ensure unions of arg types distribute correctly
  packages/template/-private/signature.d.ts
  packages/template/__tests__/component-like.test.ts
  packages/template/__tests__/helper-like.test.ts
  packages/template/__tests__/modifier-like.test.ts
  packages/template/__tests__/signature.test.ts
Labels: bug

#489 Fix #459
  packages/core/__tests__/cli/declaration.test.ts
  packages/core/src/common/transform-manager.ts
  packages/vscode/package.json
  test-packages/ts-ember-app/app/components/no-backing-module.hbs
  test-packages/ts-ember-app/tsconfig.json
  yarn.lock
Labels: bug

#492 Add an option to the Code extension for where to look for @glint/core
  docs/known-limitations.md
  packages/vscode/README.md
  packages/vscode/package.json
  packages/vscode/src/extension.ts
Labels: enhancement

#494 Remove unused `--build` suite tests
  packages/core/__tests__/cli/build.test.ts
Labels: internal

#490 Introduce `@glint/type-test` package
  .gitignore
  packages/core/__tests__/cli/build-watch.test.ts
  packages/core/__tests__/cli/build.test.ts
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/cli/custom-extensions.test.ts
  packages/core/__tests__/cli/declaration.test.ts
  packages/core/__tests__/cli/incremental.test.ts
  packages/core/__tests__/cli/watch.test.ts
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/__tests__/language-server/custom-extensions.test.ts
  packages/core/__tests__/language-server/definitions.test.ts
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/__tests__/language-server/hover.test.ts
  packages/core/__tests__/language-server/references.test.ts
  packages/core/__tests__/language-server/rename.test.ts
  packages/core/__tests__/language-server/symbol-search.test.ts
  packages/core/package.json
  packages/environment-ember-loose/package.json
  packages/environment-glimmerx/package.json
  packages/scripts/__tests__/auto-nocheck.test.ts
  packages/template/package.json
  packages/type-test/.gitignore
  packages/type-test/README.md
  packages/type-test/__tests__/classic.test.ts
  packages/type-test/__tests__/fccts.test.gts
  packages/type-test/__tests__/tsconfig.json
  packages/type-test/package.json
  packages/type-test/src/index.ts
  packages/type-test/tsconfig.json
  test-packages/test-utils/package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#495 Ensure we handle `@glint-nocheck` in composite projects correctly
  packages/core/__tests__/cli/build.test.ts
  packages/core/src/cli/perform-build-watch.ts
  packages/core/src/cli/perform-build.ts
  packages/core/src/cli/perform-watch.ts
  packages/core/src/cli/utils/patch-program.ts
  test-packages/test-utils/src/composite-project.ts
Labels: bug

#496 Update publish configuration for `@glint/type-test`
  packages/type-test/package.json
Labels: internal

#497 Fix typo in README
  packages/type-test/README.md
Labels: documentation
