Repository typed-ember/glint, pull requests merged in 2022-04, with the labels that each got.

#275 Ensure compatibility with latest upstream Ember/Glimmer types
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/package.json
  packages/template/package.json
  test-packages/ts-ember-app/package.json
  yarn.lock
Labels: bug

#276 Prevent `tsc` from inlining implementation details from upstream
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
Labels: bug

#280 Fix issue where Component super args were incorrect
  packages/environment-ember-loose/glimmer-component/index.ts
Labels: bug

#285 Expose `@glint/template` utility types
  packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
  packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
  packages/template/-private/index.d.ts
  packages/template/__tests__/component-like.test.ts
  packages/template/__tests__/helper-like.test.ts
  packages/template/__tests__/modifier-like.test.ts
  packages/template/package.json
  test-packages/ts-ember-app/app/components/bar/index.ts
  test-packages/ts-ember-app/app/components/ember-component.ts
  test-packages/ts-ember-app/app/components/foo.ts
  test-packages/ts-ember-app/app/components/qux.ts
  test-packages/ts-ember-app/app/components/template-only-module.ts
  test-packages/ts-ember-app/app/components/test-cases/subclassing/parent.ts
  test-packages/ts-ember-app/app/components/wrapper-component.ts
  test-packages/ts-ember-app/app/helpers/repeat.ts
  test-packages/ts-ember-app/app/pods/components/baz/component.ts
  test-packages/ts-ember-app/types/demo-ember-app/index.d.ts
  test-packages/ts-ember-app/types/ember-welcome-page/index.d.ts
Labels: enhancement

#287 Handle spinal-case arg names
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/template-to-typescript.ts
Labels: bug

#286 Break out README contents into GitBook docs
  .gitbook.yaml
  docs/contents.md
  docs/ember/component-signatures.md
  docs/ember/contextual-components.md
  docs/ember/imports.md
  docs/ember/installation.md
  docs/ember/rendering-tests.md
  docs/ember/routes-and-controllers.md
  docs/ember/template-only-components.md
  docs/ember/template-registry.md
  docs/ember/typing-your-dependencies.md
  docs/getting-started.md
  docs/glimmerx/component-signatures.md
  docs/glimmerx/imports.md
  docs/glimmerx/installation.md
  docs/glimmerx/template-components.md
  docs/known-limitations.md
  docs/overview.md
Labels: documentation

#288 Handle arg name position inference more carefully
  packages/transform/__tests__/offset-mapping.test.ts
  packages/transform/src/template-to-typescript.ts
Labels: bug

#289 Don't pretend the CLI can check individual files
  packages/core/src/cli/index.ts
  packages/core/src/cli/perform-check.ts
Labels: documentation

#290 Add a migration guide for native imports
  docs/contents.md
  docs/migrating.md
Labels: documentation

#291 Deprecate `environment-ember-loose` reexports
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
  packages/vscode/__fixtures__/ember-app/app/app.ts
  packages/vscode/__fixtures__/ember-app/app/components/classic-layout.ts
  packages/vscode/__fixtures__/ember-app/app/components/colocated-layout.ts
  packages/vscode/__fixtures__/ember-app/app/components/pod-layout/component.ts
Labels: documentation

#292 Migration-guide improvements
  docs/migrating.md
Labels: documentation

#296 Use `SilentError` when no config is found
  packages/config/package.json
  packages/config/src/index.ts
  packages/config/tsconfig.json
  packages/config/types/silent-error.d.ts
Labels: enhancement

#300 TypeScript upgrade
  package.json
  yarn.lock
Labels: dependencies

#306 Update to use Node 14+
  .github/workflows/ci.yml
  package.json
  test-packages/js-glimmerx-app/package.json
  test-packages/ts-ember-app/package.json
Labels: breaking

#304 Remove `environment-ember-loose` reexports
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/cli/declaration.test.ts
  packages/core/__tests__/cli/watch.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/-private/index.ts
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/-private/utilities.ts
  packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/component-like.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/helper.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/modifier.test.ts
  packages/environment-ember-loose/__tests__/type-tests/legacy-reexports/template-only.test.ts
  packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
  packages/environment-ember-loose/ember-component/-ember.ts
  packages/environment-ember-loose/ember-component/helper.ts
  packages/environment-ember-loose/ember-component/index.ts
  packages/environment-ember-loose/ember-component/template-only.ts
  packages/environment-ember-loose/ember-modifier/index.ts
  packages/environment-ember-loose/glimmer-component/index.ts
  packages/environment-ember-loose/native-integration.ts
  packages/environment-ember-loose/package.json
  packages/template/-private/index.d.ts
  packages/template/-private/integration.d.ts
  packages/template/__tests__/emit-component.test.ts
  packages/template/__tests__/helper-like.test.ts
  packages/template/__tests__/keywords/component.test.ts
  packages/template/__tests__/modifier-like.test.ts
  packages/template/__tests__/resolution.test.ts
  packages/template/__tests__/test-component.ts
  packages/template/package.json
  packages/transform/__tests__/debug.test.ts
  packages/vscode/__fixtures__/ember-app/app/app.ts
  test-packages/ts-ember-app/package.json
  test-packages/ts-ember-app/types/demo-ember-app/index.d.ts
  yarn.lock
Labels: breaking

#305 Add class-based helper to ts-ember-app test package
  test-packages/ts-ember-app/app/components/foo.hbs
  test-packages/ts-ember-app/app/helpers/affix.ts
  test-packages/ts-ember-app/tests/integration/components/foo-test.ts
Labels: internal

#308 Mark `environment-glimmerx` temporarily private to avoid publishing
  packages/environment-glimmerx/package.json
Labels: internal

#307 Update documentation for native imports & signatures
  README.md
  docs/contents.md
  docs/ember/component-signatures.md
  docs/ember/contextual-components.md
  docs/ember/helper-and-modifier-signatures.md
  docs/ember/imports.md
  docs/ember/installation.md
  docs/ember/template-only-components.md
  docs/ember/template-registry.md
  docs/ember/typing-your-dependencies.md
  docs/glimmerx/installation.md
  docs/migrating.md
Labels: documentation
