Repository typed-ember/glint, pull requests merged in 2022-10, with the labels that each got.

#421 Fix CI: Prettier on .md files
  ARCHITECTURE.md
  docs/with-js.md
Labels: internal

#422 chore: ignore Markdown files in Prettier
  .prettierignore
Labels: internal

#424 Add Common Error notes for `resolve` failures and missing `Globals` members
  docs/diagnosing-common-error-messages.md
Labels: documentation

#425 Capture embedding syntax and actual template content separately
  packages/config/src/environment.ts
  packages/core/__tests__/cli/build.test.ts
  packages/core/__tests__/utils/project.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/pool.ts
  packages/environment-ember-template-imports/-private/environment/transform.ts
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
  packages/transform/__tests__/debug.test.ts
  packages/transform/__tests__/rewrite.test.ts
  packages/transform/src/template/inlining/tagged-strings.ts
  packages/transform/src/template/map-template-contents.ts
  packages/transform/src/template/mapping-tree.ts
  packages/transform/src/template/template-to-typescript.ts
Labels: internal

#428 Honor `incremental: true` in `tsconfig.json`
  packages/core/__tests__/cli/incremental.test.ts
  packages/core/src/cli/options.ts
Labels: bug

#429 Fix `render` inference in TS 4.8+
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  test-packages/ts-ember-app/package.json
  test-packages/ts-ember-app/tests/integration/components/render-test.ts
Labels: bug

#431 Add `{{unique-id}}` to `environment-ember-loose`
  packages/environment-ember-loose/-private/dsl/globals.d.ts
  packages/environment-ember-loose/-private/intrinsics/unique-id.d.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/unique-id.test.ts
  test-packages/ts-ember-app/app/components/ember-component.hbs
Labels: enhancement

#432 Improve custom diagnostic messages
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/transform/src/diagnostics/augmentation.ts
Labels: enhancement, error messages

#435 Add missing `glob` dependency to `@glint/scripts`
  packages/scripts/package.json
Labels: bug

#440 Handle out-of-scope files more cleanly in the language server
  packages/core/__tests__/language-server/hover.test.ts
  packages/core/package.json
  packages/core/src/common/transform-manager.ts
  packages/core/src/language-server/glint-language-server.ts
  test-packages/ts-ember-app/app/components/js-component.hbs
  test-packages/ts-ember-app/app/components/js-component.js
  yarn.lock
Labels: bug

#441 Ensure we don't conflict with `declarationMap: true`
  packages/core/src/cli/options.ts
  test-packages/ts-ember-app/tsconfig.json
Labels: bug

#442 Further autocomplete improvements
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/src/language-server/binding.ts
  packages/core/src/language-server/glint-language-server.ts
Labels: bug
