Repository typed-ember/glint, pull requests merged in 2022-09, with the labels that each got.

#401 Document @glint directives, incorporating suggestions
  docs/contents.md
  docs/directives.md
Labels: documentation

#416 Remove unhelpful `glint-language-server` docs page
  docs/contents.md
  docs/glint-language-server.md
Labels: documentation

#417 Refresh `@types/node` for TS nightly fixes
  yarn.lock
Labels: internal

#402 core/cli: fix empty `.buildinfo` files with `--incremental`
  packages/core/__tests__/cli/incremental.test.ts
  packages/core/src/cli/perform-check.ts
Labels: bug

#418 Use Node 16 for development
  package.json
Labels: internal
