Repository typed-ember/glint, pull requests merged in 2022-11, with the labels that each got.

#445 Update CI config
  .github/workflows/ci.yml
Labels: internal

#451 Update addon docs with the outcome of #439
  docs/ember/authoring-addons.md
  docs/ember/using-addons.md
Labels: documentation

#452 Refresh lockfile and ensure `@types/babel__traverse` is hoisted
  package.json
  yarn.lock
Labels: internal

#456 Add support for equality operators (Ember RFC 560)
  packages/core/__tests__/transform/template-to-typescript.test.ts
  packages/core/src/config/types.cts
  packages/core/src/transform/template/template-to-typescript.ts
  packages/environment-ember-loose/-private/environment/index.ts
  packages/environment-ember-template-imports/-private/environment/index.ts
Labels: enhancement

#457 Rename block param identifiers that conflict with JS/TS keywords.
  packages/core/__tests__/transform/template-to-typescript.test.ts
  packages/core/src/transform/template/template-to-typescript.ts
Labels: bug

#458 Add an export statement to */-private/index.ts
  packages/environment-ember-loose/-private/index.ts
  packages/environment-ember-template-imports/-private/index.ts
  packages/environment-glimmerx/-private/index.ts
Labels: internal

#463 Clean up package dependencies
  README.md
  docs/ember/installation.md
  docs/getting-started.md
  docs/glimmerx/installation.md
  docs/with-js.md
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/-private/intrinsics/get.d.ts
  packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
  packages/environment-ember-loose/package.json
  packages/environment-ember-template-imports/package.json
  packages/environment-glimmerx/-private/dsl/index.d.ts
  packages/environment-glimmerx/-private/dsl/integration-declarations.d.ts
  packages/environment-glimmerx/package.json
  packages/template/-private/index.d.ts
  packages/template/-private/integration.d.ts
  packages/template/-private/signature.d.ts
  packages/template/__tests__/signature-test.test.ts
  packages/template/package.json
  packages/vscode/README.md
Labels: breaking

#465 Drop `hbs` tag support in `ember-template-imports`
  packages/core/__tests__/cli/build-watch.test.ts
  packages/core/__tests__/cli/build.test.ts
  packages/core/__tests__/cli/incremental.test.ts
  packages/core/__tests__/transform/debug.test.ts
  packages/core/__tests__/transform/rewrite.test.ts
  packages/core/src/cli/utils/patch-program.ts
  packages/core/src/cli/utils/transform-manager-pool.ts
  packages/core/src/common/transform-manager.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/transform/template/map-template-contents.ts
  packages/core/src/transform/template/template-to-typescript.ts
  packages/environment-ember-template-imports/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-template-imports/-private/environment/index.ts
  packages/environment-ember-template-imports/-private/environment/transform.ts
  test-packages/test-utils/src/composite-project.ts
Labels: breaking

#470 Validate assignability rules for `ComponentLike` and friends
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/-private/intrinsics/component.d.ts
  packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/mut.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/outlet.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/unbound.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/unique-id.test.ts
  packages/environment-ember-loose/__tests__/type-tests/route-and-controller.test.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
  packages/environment-ember-template-imports/-private/dsl/index.d.ts
  packages/environment-glimmerx/-private/dsl/index.d.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/environment-glimmerx/__tests__/helper.test.ts
  packages/template/-private/dsl/emit.d.ts
  packages/template/-private/integration.d.ts
  packages/template/-private/signature.d.ts
  packages/template/__tests__/component-like.test.ts
  packages/template/__tests__/helper-like.test.ts
  packages/template/__tests__/modifier-like.test.ts
  packages/template/__tests__/signature-test.test.ts
  packages/template/__tests__/test-component.ts
  test-packages/ts-ember-app/tests/integration/types/empty-signature-test.ts
Labels: breaking

#472 Honor lowercase in-scope variables when used as components
  packages/core/__tests__/transform/template-to-typescript.test.ts
  packages/core/src/transform/template/template-to-typescript.ts
Labels: bug

#473 Support the `ShowIR` command for non-`.ts` files
  .vscode/launch.json
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/messages.ts
  packages/vscode/__tests__/smoketest-ember.test.ts
  packages/vscode/__tests__/smoketest-template-imports.test.ts
  packages/vscode/src/extension.ts
Labels: enhancement

#474 Add migration notes for 0.9 => 1.0
  docs/migrating.md
  package.json
  yarn.lock
Labels: documentation

#475 Disable anti-classic ESLint rules for `ts-ember-preview-types` test package
  test-packages/ts-ember-preview-types/.eslintrc.js
  test-packages/ts-ember-preview-types/app/components/bar/index.ts
  test-packages/ts-ember-preview-types/app/components/ember-component.ts
  test-packages/ts-ember-preview-types/app/components/foo.ts
  test-packages/ts-ember-preview-types/app/components/qux.ts
  test-packages/ts-ember-preview-types/app/components/test-cases/subclassing/parent.ts
  test-packages/ts-ember-preview-types/app/components/wrapper-component.ts
  test-packages/ts-ember-preview-types/app/pods/components/baz/component.ts
Labels: internal

#479 Make the Code extension publishable
  packages/core/package.json
  packages/core/src/language-server/binding.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/messages.cts
  packages/vscode/.gitignore
  packages/vscode/.vscodeignore
  packages/vscode/__tests__/support/launch-from-cli.mjs
  packages/vscode/jest.config.mjs
  packages/vscode/package.json
  packages/vscode/src/entry.cts
  packages/vscode/src/extension.ts
  packages/vscode/tsconfig.json
  yarn.lock
Labels: bug

#482 Update minimum supported TS version to 4.8
  docs/ember/installation.md
  docs/glimmerx/installation.md
  docs/migrating.md
  package.json
  packages/core/package.json
  packages/scripts/package.json
  yarn.lock
Labels: breaking

#483 Fix up a couple ESM oddities in the CLI
  packages/core/src/cli/index.ts
Labels: bug

#484 Ensure `link-to` can still be invoked with only named args
  packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/link-to.test.ts
Labels: bug
