Repository typed-ember/glint, pull requests merged in 2022-08, with the labels that each got.

#377 Add support for project references and `--build`
  .prettierignore
  docs/configuration/_index.md
  docs/configuration/project-references.md
  docs/contents.md
  docs/known-limitations.md
  package.json
  packages/config/src/index.ts
  packages/config/src/loader.ts
  packages/core/__tests__/cli/build-watch.test.ts
  packages/core/__tests__/cli/build.test.ts
  packages/core/__tests__/utils/project.ts
  packages/core/src/cli/diagnostics.ts
  packages/core/src/cli/index.ts
  packages/core/src/cli/perform-build-watch.ts
  packages/core/src/cli/perform-build.ts
  packages/core/src/cli/perform-check.ts
  packages/core/src/cli/perform-watch.ts
  packages/core/src/cli/utils/assert.ts
  packages/core/src/cli/utils/patch-program.ts
  packages/core/src/cli/utils/sys-for-compiler-host.ts
  packages/core/src/cli/utils/transform-manager-pool.ts
  yarn.lock
Labels: enhancement

#382 core/cli: implement `glint --build --force`
  packages/core/__tests__/cli/build.test.ts
  packages/core/src/cli/index.ts
Labels: enhancement

#381 core/cli: implement `glint --build --clean`
  packages/core/__tests__/cli/build.test.ts
  packages/core/src/cli/index.ts
Labels: enhancement

#385 Handle TS nightly changes to declaration emit
  packages/core/__tests__/cli/declaration.test.ts
  packages/core/__tests__/utils/project.ts
Labels: internal

#383 core/cli: implement `glint --build --dry`
  packages/config/__tests__/environment.test.ts
  packages/config/__tests__/load-config.test.ts
  packages/config/__tests__/loader.test.ts
  packages/config/package.json
  packages/core/__tests__/cli/build.test.ts
  packages/core/__tests__/utils/project.ts
  packages/core/package.json
  packages/core/src/cli/index.ts
  packages/core/src/cli/perform-build.ts
  packages/core/src/cli/utils/sys-for-compiler-host.ts
  packages/core/src/cli/utils/transform-manager-pool.ts
  packages/core/src/common/transform-manager.ts
  packages/environment-ember-loose/package.json
  packages/environment-ember-template-imports/package.json
  packages/scripts/package.json
  packages/transform/package.json
  yarn.lock
Labels: enhancement

#384 Remove GlimmerX shims
  docs/configuration/project-references.md
  docs/contents.md
  docs/glimmerx/component-signatures.md
  docs/glimmerx/imports.md
  docs/glimmerx/installation.md
  docs/glimmerx/template-components.md
  package.json
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/cli/declaration.test.ts
  packages/core/__tests__/cli/watch.test.ts
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/__tests__/language-server/definitions.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/__tests__/language-server/hover.test.ts
  packages/core/__tests__/language-server/references.test.ts
  packages/core/__tests__/language-server/rename.test.ts
  packages/core/__tests__/language-server/symbol-search.test.ts
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/__tests__/type-tests/route-and-controller.test.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
  packages/environment-glimmerx/-private/dsl/index.d.ts
  packages/environment-glimmerx/-private/dsl/integration-declarations.d.ts
  packages/environment-glimmerx/-private/environment/index.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/environment-glimmerx/__tests__/helper.test.ts
  packages/environment-glimmerx/__tests__/modifier.test.ts
  packages/environment-glimmerx/component/index.ts
  packages/environment-glimmerx/helper/index.ts
  packages/environment-glimmerx/modifier/index.ts
  packages/environment-glimmerx/package.json
  packages/template/-private/dsl/emit.d.ts
  packages/template/-private/integration.d.ts
  packages/template/package.json
  packages/transform/__tests__/debug.test.ts
  packages/transform/__tests__/offset-mapping.test.ts
  packages/transform/__tests__/rewrite.test.ts
  packages/vscode/__fixtures__/js-glimmerx-app/src/SimpleComponent.js
  packages/vscode/__fixtures__/js-glimmerx-app/tests/integration/component-test.js
  packages/vscode/__fixtures__/template-imports-app/src/Greeting.gts
  packages/vscode/__tests__/smoketest-js-glimmerx.test.ts
  test-packages/js-glimmerx-app/.babelrc.js
  test-packages/js-glimmerx-app/package.json
  test-packages/js-glimmerx-app/src/App.js
  test-packages/js-glimmerx-app/src/GreetingHeader.js
  test-packages/js-glimmerx-app/tests/rendering/component.test.js
  test-packages/ts-ember-app/types/ts-ember-app/index.d.ts
  test-packages/ts-glimmerx-app/.babelrc.js
  test-packages/ts-glimmerx-app/package.json
  test-packages/ts-glimmerx-app/src/App.ts
  test-packages/ts-glimmerx-app/src/GreetingHeader.ts
  yarn.lock
Labels: enhancement

#386 core/cli: add `glint --incremental` support
  packages/core/__tests__/cli/incremental.test.ts
  packages/core/src/cli/index.ts
  packages/core/src/cli/options.ts
Labels: enhancement

#390 Break `template()` in two
  packages/core/__tests__/cli/declaration.test.ts
  packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/route-and-controller.test.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
  packages/environment-ember-template-imports/-private/dsl/index.d.ts
  packages/environment-glimmerx/-private/dsl/index.d.ts
  packages/environment-glimmerx/__tests__/component.test.ts
  packages/template/-private/dsl/emit.d.ts
  packages/template/-private/dsl/types.d.ts
  packages/template/__tests__/attributes.test.ts
  packages/template/__tests__/emit-component.test.ts
  packages/template/__tests__/resolution.test.ts
  packages/transform/__tests__/debug.test.ts
  packages/transform/__tests__/offset-mapping.test.ts
  packages/transform/__tests__/rewrite.test.ts
  packages/transform/__tests__/template-to-typescript.test.ts
  packages/transform/src/template/inlining/companion-file.ts
  packages/transform/src/template/inlining/index.ts
  packages/transform/src/template/inlining/tagged-strings.ts
  packages/transform/src/template/template-to-typescript.ts
  packages/vscode/__tests__/helpers/async.ts
  test-packages/ts-glimmerx-app/src/App.ts
  test-packages/ts-template-imports-app/src/Playground.gts
Labels: bug

#391 Avoid trying to load a local TypeScript instance from the LSP
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/util/protocol.ts
Labels: bug

#392 Start publishing `@glint/environment-glimmerx` again
  packages/environment-glimmerx/README.md
  packages/environment-glimmerx/package.json
Labels: enhancement

#394 Explicitly document our expected peer versions
  docs/ember/installation.md
  docs/glimmerx/installation.md
  packages/core/package.json
  packages/environment-glimmerx/package.json
Labels: documentation
