Repository typed-ember/glint, pull requests merged in 2022-05, with the labels that each got.

#316 Handle explicit `Args: {}` and similar
  packages/template/-private/index.d.ts
  packages/template/-private/integration.d.ts
  test-packages/ts-ember-app/tests/integration/types/empty-signature-test.ts
Labels: bug

#313 Add addon documentation
  docs/contents.md
  docs/ember/authoring-addons.md
  docs/ember/typing-your-dependencies.md
  docs/ember/using-addons.md
  docs/overview.md
Labels: documentation

#328 Fix name of environment-ember-loose main function
  packages/environment-ember-loose/-private/environment/index.ts
Labels: internal

#329 Make Ember template-only components ComponentLike
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
Labels: bug

#336 Don't flood the language server work queue when many changes come in
  packages/core/src/common/scheduling.ts
Labels: bug

#335 Account for leading trivia in source files for LSP diagnostic locations
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/language-server/glint-language-server.ts
Labels: bug

#333 Integrate `@glint/environment-ember-template-imports`
  packages/core/__tests__/cli/check.test.ts
  packages/core/__tests__/cli/custom-extensions.test.ts
  packages/core/__tests__/cli/watch.test.ts
  packages/core/__tests__/language-server/custom-extensions.test.ts
  packages/environment-ember-template-imports/-private/dsl/globals.d.ts
  packages/environment-ember-template-imports/-private/dsl/index.d.ts
  packages/environment-ember-template-imports/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-template-imports/-private/environment/common.ts
  packages/environment-ember-template-imports/-private/environment/index.ts
  packages/environment-ember-template-imports/-private/environment/preprocess.ts
  packages/environment-ember-template-imports/-private/environment/transform.ts
  packages/environment-ember-template-imports/-private/index.ts
  packages/environment-ember-template-imports/.eslintignore
  packages/environment-ember-template-imports/.gitignore
  packages/environment-ember-template-imports/.prettierignore
  packages/environment-ember-template-imports/README.md
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
  packages/environment-ember-template-imports/jest.config.js
  packages/environment-ember-template-imports/package.json
  packages/environment-ember-template-imports/tsconfig.json
  packages/transform/__tests__/rewrite.test.ts
  packages/transform/src/index.ts
  packages/vscode/__fixtures__/custom-app/.glintrc.yml
  packages/vscode/__fixtures__/template-imports-app/.glintrc.yml
  packages/vscode/__fixtures__/template-imports-app/package.json
  packages/vscode/__fixtures__/template-imports-app/src/Greeting.gts
  packages/vscode/__fixtures__/template-imports-app/src/index.gts
  packages/vscode/__fixtures__/template-imports-app/tsconfig.json
  packages/vscode/__tests__/smoketest-template-imports.test.ts
  packages/vscode/__tests__/support/launch-from-cli.js
  test-packages/glint-environment-custom-test/env.js
  test-packages/glint-environment-custom-test/package.json
  test-packages/glint-test-packages.code-workspace
  test-packages/ts-custom-app/.glintrc.yml
  test-packages/ts-custom-app/src/Greeting.custom
  test-packages/ts-template-imports-app/.gitignore
  test-packages/ts-template-imports-app/.glintrc.yml
  test-packages/ts-template-imports-app/package.json
  test-packages/ts-template-imports-app/src/Greeting.gts
  test-packages/ts-template-imports-app/src/index.gts
  test-packages/ts-template-imports-app/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: enhancement
