Repository typed-ember/glint, pull requests merged in 2023-04, with the labels that each got.

#554 Switch to a maintained XVFB action in CI
  .github/workflows/ci.yml
Labels: internal

#558 Allow `each-in` to accept `key` as a named arg
  packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/each-in.test.ts
Labels: enhancement

#561 Bugfixes for the beta.5 `bind-invokable` refactor
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/src/transform/diagnostics/augmentation.ts
  packages/core/src/transform/template/template-to-typescript.ts
  packages/environment-ember-loose/-private/dsl/index.d.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/component.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/helper.test.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/modifier.test.ts
  packages/template/-private/keywords/-bind-invokable.d.ts
  packages/template/__tests__/keywords/component.test.ts
Labels: bug

#562 1.0 Docs Updates
  README.md
  docs/contents.md
  docs/diagnosing-common-error-messages.md
  docs/directives.md
  docs/ember/authoring-addons.md
  docs/ember/installation.md
  docs/glint-types.md
  docs/known-limitations.md
  docs/migrating.md
  docs/overview.md
Labels: documentation

#563 [Bugfix] Drop `allowPlainFunctionInvocation` flag
  docs/ember/installation.md
  docs/migrating.md
  packages/environment-ember-loose/-private/dsl/index.d.ts
  packages/environment-ember-loose/-private/dsl/without-function-resolution.d.ts
  packages/environment-ember-loose/-private/environment/index.ts
  packages/environment-ember-loose/__tests__/environment.test.ts
  packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
  packages/environment-ember-loose/package.json
Labels: bug

#567 Don't pollute completions with globals in templates with syntax errors
  packages/core/__tests__/language-server/completions.test.ts
  packages/core/src/common/transform-manager.ts
  packages/core/src/language-server/glint-language-server.ts
Labels: bug
