Repository typed-ember/glint, pull requests merged in 2023-01, with the labels that each got.

#511 Add documentation note about error substate routes
  docs/ember/routes-and-controllers.md
Labels: documentation

#510 Add support for logical operators (RFC 562)
  packages/core/__tests__/transform/template-to-typescript.test.ts
  packages/core/src/config/types.cts
  packages/core/src/transform/template/template-to-typescript.ts
Labels: enhancement

#499 Introduce CodeActions
  packages/core/__tests__/language-server/custom-extensions.test.ts
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/language-server/binding.ts
  packages/core/src/language-server/config-manager.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/index.ts
  packages/core/src/transform/template/transformed-module.ts
  packages/vscode/__tests__/smoketest-ember.test.ts
  packages/vscode/__tests__/smoketest-js-glimmerx.test.ts
  packages/vscode/__tests__/smoketest-template-imports.test.ts
  packages/vscode/src/extension.ts
Labels: enhancement

#498 Widen supported range for ember-modifier to include v4
  packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
  packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
  packages/environment-ember-loose/package.json
  test-packages/ts-ember-app/package.json
  yarn.lock
Labels: enhancement

#523 Validate that TS meets our minimum supported version requirement
  packages/core/package.json
  packages/core/src/cli/index.ts
  packages/core/src/common/typescript-compatibility.ts
  packages/core/src/language-server/pool.ts
  yarn.lock
Labels: enhancement

#520 Honor user formatting preferences in completions
  packages/core/src/language-server/binding.ts
  packages/core/src/language-server/glint-language-server.ts
Labels: enhancement

#500 Ensure adding/removing directives busts any cached typecheck results
  packages/core/__tests__/cli/build-watch.test.ts
  packages/core/__tests__/transform/debug.test.ts
  packages/core/__tests__/transform/template-to-typescript.test.ts
  packages/core/src/transform/template/template-to-typescript.ts
Labels: bug

#527 Use `{{get}}` notation in `noPropertyAccessFromIndexSignature` diagnostics
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/src/transform/diagnostics/augmentation.ts
  test-packages/test-utils/src/project.ts
Labels: error messages

#528 Don't duplicate diagnostic code information
  packages/core/__tests__/language-server/custom-extensions.test.ts
  packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
  packages/core/__tests__/language-server/diagnostics.test.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/vscode/__tests__/smoketest-ember.test.ts
  packages/vscode/__tests__/smoketest-js-glimmerx.test.ts
  packages/vscode/__tests__/smoketest-template-imports.test.ts
Labels: bug
