Repository typed-ember/glint, pull requests merged in 2023-11, with the labels that each got.

#650 Lock @types/node to avoid issues in floating-dependencies CI
  package.json
  yarn.lock
Labels: internal

#635 Add "Sort Imports" command to vscode extension & lsp
  packages/core/__tests__/language-server/organize-imports.test.ts
  packages/core/src/language-server/binding.ts
  packages/core/src/language-server/glint-language-server.ts
  packages/core/src/language-server/messages.cts
  packages/vscode/package.json
  packages/vscode/src/extension.ts
Labels: enhancement

#654 docs: fix typo
  docs/ember/template-imports.md
Labels: documentation
