Repository typed-ember/glint, pull requests merged in 2025-04, with the labels that each got.

#872 Remove `export default` from the Template-only components example
  docs/ember/template-imports.md
Labels: documentation

#881 Consolidate scripts, add generated files to eslint/prettier ignore file
  .eslintignore
  .gitignore
  .prettierignore
  bin/build-augmentations.mjs
  bin/build-elements.mjs
  package.json
  packages/template/-private/dsl/elements.d.ts
  packages/template/-private/dsl/lib.dom.augmentation.d.ts
  pnpm-lock.yaml
  test-packages/package-test-core/__tests__/language-server/diagnostic-augmentation.test.ts
Labels: internal

#883 Add character tests
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
  test-packages/package-test-core/__tests__/language-server/diagnostic-augmentation.test.ts
  test-packages/package-test-core/__tests__/transform/rewrite.test.ts
Labels: internal

#880 fix missing generic attrs for svg
  bin/build-elements.mjs
  packages/template/-private/dsl/elements.d.ts
  test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts
Labels: bug
