Repository typed-ember/glint, pull requests merged in 2025-03, with the labels that each got.

#826 Explicitly accept an Iterable in `each-in`
  packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
  packages/environment-ember-loose/__tests__/type-tests/intrinsics/each-in.test.ts
Labels: bug

#832 Update Glint v2 docs
  GLINT_V2.md
Labels: documentation

#831 Setup release-plan for releases
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .release-it.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  packages/vscode/package.json
  pnpm-lock.yaml
Labels: internal

#834 Make the test-apps private
  test-packages/ts-plugin-test-app/package.json
Labels: internal

#836 Update GLINT_V2.md readme
  GLINT_V2.md
Labels: documentation

#838 Support extending multiple config files
  packages/core/__tests__/config/load-config.test.ts
  packages/core/src/config/loader.ts
Labels: enhancement

#848 Escape and transform template string
  packages/core/__tests__/transform/rewrite.test.ts
  packages/environment-ember-template-imports/-private/environment/preprocess.ts
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
Labels: bug

#842 Improve multi-byte character handling
  packages/core/__tests__/transform/rewrite.test.ts
  packages/environment-ember-template-imports/-private/environment/preprocess.ts
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
Labels: bug

#850 Update info about not disabling the `@builtin typescript` extension forV2
  packages/vscode/README.md
Labels: documentation

#843 Move core tests out of core package due to tests depending on packages that depend on core
  .prettierignore
  packages/core/__tests__/tsconfig.json
  packages/core/package.json
  pnpm-lock.yaml
  test-packages/package-test-core/__tests__/cli/build-watch.test.ts
  test-packages/package-test-core/__tests__/cli/build.test.ts
  test-packages/package-test-core/__tests__/cli/check-watch.test.ts
  test-packages/package-test-core/__tests__/cli/check.test.ts
  test-packages/package-test-core/__tests__/cli/declaration.test.ts
  test-packages/package-test-core/__tests__/cli/incremental.test.ts
  test-packages/package-test-core/__tests__/config/environment.test.ts
  test-packages/package-test-core/__tests__/config/load-config.test.ts
  test-packages/package-test-core/__tests__/config/loader.test.ts
  test-packages/package-test-core/__tests__/language-server/completions.test.ts
  test-packages/package-test-core/__tests__/language-server/definitions.test.ts
  test-packages/package-test-core/__tests__/language-server/diagnostic-augmentation.test.ts
  test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts
  test-packages/package-test-core/__tests__/language-server/hover.test.ts
  test-packages/package-test-core/__tests__/language-server/references.test.ts
  test-packages/package-test-core/__tests__/language-server/rename.test.ts
  test-packages/package-test-core/__tests__/support/character-position-viewer.html
  test-packages/package-test-core/__tests__/transform/offset-mapping.test.ts
  test-packages/package-test-core/__tests__/transform/rewrite.test.ts
  test-packages/package-test-core/__tests__/transform/template-to-typescript.test.ts
  test-packages/package-test-core/package.json
  test-packages/package-test-core/tsconfig.json
  test-packages/package-test-core/vitest.config.ts
Labels: internal

#858 Disable esModuleInterop to restore VSCode monkeypatching
  packages/vscode/src/extension.ts
  tsconfig.compileroptions.json
Labels: bug

#857 Setup external project linking / testing
  .eslintrc
  .gitignore
  CONTRIBUTING.md
  bin/link-build.mjs
  bin/link-install.mjs
  bin/packages.mjs
  package.json
  packages/environment-ember-loose/package.json
  packages/environment-ember-template-imports/package.json
  packages/type-test/package.json
  pnpm-lock.yaml
Labels: internal

#856 Support (neo)vim filetypes for gts and gjs
  packages/core/src/volar/ember-language-plugin.ts
  packages/core/src/volar/gts-virtual-code.ts
  test-packages/package-test-core/__tests__/language-server/definitions.test.ts
Labels: enhancement

#860 Only transform expression satisfies templates
  packages/environment-ember-template-imports/-private/environment/transform.ts
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
Labels: bug

#859 Fix handling of `satisfies` on components.
  packages/environment-ember-template-imports/-private/environment/transform.ts
  packages/environment-ember-template-imports/__tests__/transformation.test.ts
  test-packages/package-test-core/__tests__/transform/rewrite.test.ts
Labels: bug

#862 Use the tars directly, rather than links
  bin/link-build.mjs
  bin/link-install.mjs
  package.json
  pnpm-lock.yaml
Labels: internal

#849 add html attribute validation & completions
  .eslintignore
  .eslintrc
  package.json
  packages/core/src/transform/template/template-to-typescript.ts
  packages/template/-private/dsl/elements.d.ts
  packages/template/-private/dsl/emit.d.ts
  packages/template/-private/dsl/lib.dom.augmentation.d.ts
  packages/template/-private/dsl/types.d.ts
  packages/template/__tests__/attributes.test.ts
  packages/template/package.json
  packages/tsserver-plugin/src/typescript-server-plugin.ts
  pnpm-lock.yaml
  scripts/build-augmentations.mjs
  scripts/build-elements.mjs
  test-packages/package-test-core/__tests__/language-server/diagnostic-augmentation.test.ts
  test-packages/package-test-core/__tests__/transform/rewrite.test.ts
  test-packages/package-test-core/__tests__/transform/template-to-typescript.test.ts
  test-packages/ts-plugin-test-app/src/glimmer.gts
Labels: enhancement

#865 Prefer variables in scope over global variables
  packages/core/src/transform/template/template-to-typescript.ts
  test-packages/package-test-core/__tests__/transform/template-to-typescript.test.ts
Labels: bug
