Repository typed-ember/glint, pull requests merged in 2025-10, with the labels that each got.

#985 Typo in README.md
  packages/core/README.md
Labels: documentation

#986 Add missing "xmlns" attribut to SVGSVGElementAttributes
  packages/template/-private/dsl/elements.d.ts
Labels: bug

#987 Listed ember-codemod-add-template-tags as a migration option
  docs/v2-upgrade.md
Labels: documentation

#989 Allow V2 addons to get .d.ts declarations instead of .gts.d.ts
  packages/core/src/cli/run-volar-tsc.ts
Labels: bug

#994 Update README to reflect Glint 2 status
  README.md
Labels: documentation

#996 Delete GLINT_V2.md
  GLINT_V2.md
Labels: documentation

#997 Fix some typos in upgrade guide
  docs/v2-upgrade.md
Labels: documentation

#998 Add another test project for assuring we build declarations correctly
  .eslintignore
  .github/workflows/ci.yml
  .prettierignore
  package.json
  pnpm-lock.yaml
  test-packages/v2-ts-ember-addon/.editorconfig
  test-packages/v2-ts-ember-addon/.env.development
  test-packages/v2-ts-ember-addon/.gitignore
  test-packages/v2-ts-ember-addon/.prettierignore
  test-packages/v2-ts-ember-addon/.prettierrc.cjs
  test-packages/v2-ts-ember-addon/.template-lintrc.cjs
  test-packages/v2-ts-ember-addon/.try.mjs
  test-packages/v2-ts-ember-addon/CONTRIBUTING.md
  test-packages/v2-ts-ember-addon/LICENSE.md
  test-packages/v2-ts-ember-addon/README.md
  test-packages/v2-ts-ember-addon/addon-main.cjs
  test-packages/v2-ts-ember-addon/babel.config.cjs
  test-packages/v2-ts-ember-addon/babel.publish.config.cjs
  test-packages/v2-ts-ember-addon/config/ember-cli-update.json
  test-packages/v2-ts-ember-addon/eslint.config.mjs
  test-packages/v2-ts-ember-addon/package.json
  test-packages/v2-ts-ember-addon/rollup.config.mjs
  test-packages/v2-ts-ember-addon/src/foo.gts
  test-packages/v2-ts-ember-addon/src/index.ts
  test-packages/v2-ts-ember-addon/src/template-registry.ts
  test-packages/v2-ts-ember-addon/test-build.mjs
  test-packages/v2-ts-ember-addon/testem.cjs
  test-packages/v2-ts-ember-addon/tests/index.html
  test-packages/v2-ts-ember-addon/tests/test-helper.ts
  test-packages/v2-ts-ember-addon/tsconfig.json
  test-packages/v2-ts-ember-addon/tsconfig.publish.json
  test-packages/v2-ts-ember-addon/unpublished-development-types/index.d.ts
  test-packages/v2-ts-ember-addon/vite.config.mjs
Labels: internal
